/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { BodyModule } from '@radzen/angular/dist/body';
import { CardModule } from '@radzen/angular/dist/card';
import { ContentContainerModule } from '@radzen/angular/dist/content-container';
import { HeaderModule } from '@radzen/angular/dist/header';
import { SidebarToggleModule } from '@radzen/angular/dist/sidebar-toggle';
import { LabelModule } from '@radzen/angular/dist/label';
import { SidebarModule } from '@radzen/angular/dist/sidebar';
import { PanelMenuModule } from '@radzen/angular/dist/panelmenu';
import { FooterModule } from '@radzen/angular/dist/footer';
import { ContentModule } from '@radzen/angular/dist/content';
import { HeadingModule } from '@radzen/angular/dist/heading';
import { GridModule } from '@radzen/angular/dist/grid';
import { FormModule } from '@radzen/angular/dist/form';
import { SchedulerModule } from '@radzen/angular/dist/scheduler';
import { SharedModule } from '@radzen/angular/dist/shared';
import { NotificationModule } from '@radzen/angular/dist/notification';
import { DialogModule } from '@radzen/angular/dist/dialog';

import { ConfigService, configServiceFactory } from './config.service';
import { AppRoutes } from './app.routes';
import { AppComponent } from './app.component';
import { CacheInterceptor } from './cache.interceptor';
export { AppComponent } from './app.component';
import { EquipamentosComponent } from './equipamentos/equipamentos.component';
import { AddEquipamentoComponent } from './add-equipamento/add-equipamento.component';
import { EditEquipamentoComponent } from './edit-equipamento/edit-equipamento.component';
import { EstaAtribuidosComponent } from './esta-atribuidos/esta-atribuidos.component';
import { AddEstaAtribuidoComponent } from './add-esta-atribuido/add-esta-atribuido.component';
import { EditEstaAtribuidoComponent } from './edit-esta-atribuido/edit-esta-atribuido.component';
import { FormacaosComponent } from './formacaos/formacaos.component';
import { GtsComponent } from './gts/gts.component';
import { AddGtComponent } from './add-gt/add-gt.component';
import { EditGtComponent } from './edit-gt/edit-gt.component';
import { InstituicaosComponent } from './instituicaos/instituicaos.component';
import { AddInstituicaoComponent } from './add-instituicao/add-instituicao.component';
import { EditInstituicaoComponent } from './edit-instituicao/edit-instituicao.component';
import { PedesComponent } from './pedes/pedes.component';
import { AddPedeComponent } from './add-pede/add-pede.component';
import { EditPedeComponent } from './edit-pede/edit-pede.component';
import { PertenceUisComponent } from './pertence-uis/pertence-uis.component';
import { AddPertenceUiComponent } from './add-pertence-ui/add-pertence-ui.component';
import { EditPertenceUiComponent } from './edit-pertence-ui/edit-pertence-ui.component';
import { PertencersComponent } from './pertencers/pertencers.component';
import { AddPertencerComponent } from './add-pertencer/add-pertencer.component';
import { EditPertencerComponent } from './edit-pertencer/edit-pertencer.component';
import { PessoasComponent } from './pessoas/pessoas.component';
import { AddPessoaComponent } from './add-pessoa/add-pessoa.component';
import { EditPessoaComponent } from './edit-pessoa/edit-pessoa.component';
import { ProdutosComponent } from './produtos/produtos.component';
import { RecursosComponent } from './recursos/recursos.component';
import { AddRecursoComponent } from './add-recurso/add-recurso.component';
import { EditRecursoComponent } from './edit-recurso/edit-recurso.component';
import { ServicosComponent } from './servicos/servicos.component';
import { AddServicoComponent } from './add-servico/add-servico.component';
import { EditServicoComponent } from './edit-servico/edit-servico.component';
import { UisComponent } from './uis/uis.component';
import { AddUiComponent } from './add-ui/add-ui.component';
import { EditUiComponent } from './edit-ui/edit-ui.component';
import { ServicoCalendarComponent } from './servico-calendar/servico-calendar.component';
import { LoginLayoutComponent } from './login-layout/login-layout.component';
import { MainLayoutComponent } from './main-layout/main-layout.component';

import { ProjetoNewService } from './projeto-new.service';

export const PageDeclarations = [
  EquipamentosComponent,
  AddEquipamentoComponent,
  EditEquipamentoComponent,
  EstaAtribuidosComponent,
  AddEstaAtribuidoComponent,
  EditEstaAtribuidoComponent,
  FormacaosComponent,
  GtsComponent,
  AddGtComponent,
  EditGtComponent,
  InstituicaosComponent,
  AddInstituicaoComponent,
  EditInstituicaoComponent,
  PedesComponent,
  AddPedeComponent,
  EditPedeComponent,
  PertenceUisComponent,
  AddPertenceUiComponent,
  EditPertenceUiComponent,
  PertencersComponent,
  AddPertencerComponent,
  EditPertencerComponent,
  PessoasComponent,
  AddPessoaComponent,
  EditPessoaComponent,
  ProdutosComponent,
  RecursosComponent,
  AddRecursoComponent,
  EditRecursoComponent,
  ServicosComponent,
  AddServicoComponent,
  EditServicoComponent,
  UisComponent,
  AddUiComponent,
  EditUiComponent,
  ServicoCalendarComponent,
];

export const LayoutDeclarations = [
  LoginLayoutComponent,
  MainLayoutComponent,
];

export const AppDeclarations = [
  ...PageDeclarations,
  ...LayoutDeclarations,
  AppComponent
];

export const AppProviders = [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: CacheInterceptor,
    multi: true
  },
  ProjetoNewService,
  ConfigService,
  {
    provide: APP_INITIALIZER,
    useFactory: configServiceFactory,
    deps: [ConfigService],
    multi: true
  }
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  BodyModule,
  CardModule,
  ContentContainerModule,
  HeaderModule,
  SidebarToggleModule,
  LabelModule,
  SidebarModule,
  PanelMenuModule,
  FooterModule,
  ContentModule,
  HeadingModule,
  GridModule,
  FormModule,
  SchedulerModule,
  SharedModule,
  NotificationModule,
  DialogModule,
  AppRoutes
];
